/* Lote 2 — quiet section backgrounds (WebGL1 / GLSL ES 1.00)
 * Design: soft fields, low amplitude, muted neon, gentle grain.
 * Glitch = micro RGB / soft tears / brief scan corruption — NOT Glitch City.
 */
window.SHADER_LOTE_2 = [
  {
    id: "soft-vein-glow",
    name: "Soft Vein Glow",
    lote: 2,
    mood: "muted plasma · organic haze · content-safe glow",
    keywords: ["plasma", "veins", "soft", "organic", "muted"],
    traits: ["plasma", "veins", "soft", "organic", "muted", "density-low", "magenta", "section-bg"],
    palette: ["#07060c", "#4a1a3a", "#7a3a5a", "#1a1020", "#2a1830"],
    motion: "Very slow domain-warped veins at low contrast; no bright hotspots.",
    performance: "Medium-light — 3-octave fbm, keep DPR capped on mobile.",
    fragment: [
      "precision mediump float;",
      "uniform float u_time;",
      "uniform vec2 u_resolution;",
      "varying vec2 v_uv;",
      "float hash(vec2 p){ return fract(sin(dot(p, vec2(127.1,311.7))) * 43758.5453); }",
      "float noise(vec2 p){",
      "  vec2 i=floor(p); vec2 f=fract(p);",
      "  float a=hash(i); float b=hash(i+vec2(1.0,0.0));",
      "  float c=hash(i+vec2(0.0,1.0)); float d=hash(i+vec2(1.0,1.0));",
      "  vec2 u=f*f*(3.0-2.0*f);",
      "  return mix(mix(a,b,u.x), mix(c,d,u.x), u.y);",
      "}",
      "float fbm(vec2 p){",
      "  float v=0.0; float a=0.5;",
      "  for(int i=0;i<3;i++){ v+=a*noise(p); p*=2.03; a*=0.5; }",
      "  return v;",
      "}",
      "void main(){",
      "  vec2 uv=(gl_FragCoord.xy-0.5*u_resolution.xy)/u_resolution.y;",
      "  float t=u_time*0.12;",
      "  vec2 p=uv*1.6;",
      "  vec2 q=vec2(fbm(p+t), fbm(p+vec2(3.1,1.4)-t*0.7));",
      "  float f=fbm(p+1.8*q);",
      "  float veins=smoothstep(0.35, 0.55, 1.0-abs(f*2.0-1.0));",
      "  vec3 col=vec3(0.035, 0.03, 0.05);",
      "  col+=vec3(0.28, 0.08, 0.18)*veins*0.35;",
      "  col+=vec3(0.12, 0.05, 0.22)*f*0.18;",
      "  col+=vec3(0.04, 0.03, 0.06)*(0.5+0.5*sin(t+f*3.0))*0.15;",
      "  col*=smoothstep(1.45, 0.35, length(uv*vec2(0.85,1.0)));",
      "  gl_FragColor=vec4(col,1.0);",
      "}"
    ].join("\n")
  },
  {
    id: "mist-scanfield",
    name: "Mist Scanfield",
    lote: 2,
    mood: "fog wash · soft phosphor · quiet CRT breath",
    keywords: ["fog", "scanline", "mist", "phosphor", "soft"],
    traits: ["fog", "scanline", "mist", "phosphor", "soft", "density-low", "blue", "section-bg"],
    palette: ["#06080c", "#1a2830", "#3a5060", "#8aa8b8", "#0c1014"],
    motion: "Drifting soft fog with barely-visible scanlines and slow roll.",
    performance: "Light — few noise samples.",
    fragment: [
      "precision mediump float;",
      "uniform float u_time;",
      "uniform vec2 u_resolution;",
      "varying vec2 v_uv;",
      "float hash(vec2 p){ return fract(sin(dot(p, vec2(127.1,311.7))) * 43758.5453); }",
      "float noise(vec2 p){",
      "  vec2 i=floor(p); vec2 f=fract(p);",
      "  float a=hash(i); float b=hash(i+vec2(1.0,0.0));",
      "  float c=hash(i+vec2(0.0,1.0)); float d=hash(i+vec2(1.0,1.0));",
      "  vec2 u=f*f*(3.0-2.0*f);",
      "  return mix(mix(a,b,u.x), mix(c,d,u.x), u.y);",
      "}",
      "void main(){",
      "  vec2 p=(gl_FragCoord.xy-0.5*u_resolution.xy)/u_resolution.y;",
      "  float t=u_time*0.08;",
      "  float n1=noise(p*1.2+vec2(t, t*0.6));",
      "  float n2=noise(p*2.4-vec2(t*0.5, -t*0.4));",
      "  float fog=smoothstep(0.25, 0.75, n1*0.55+n2*0.45);",
      "  vec3 col=vec3(0.04, 0.05, 0.07);",
      "  col+=vec3(0.18, 0.28, 0.36)*fog*0.28;",
      "  col+=vec3(0.25, 0.35, 0.42)*pow(fog, 2.5)*0.12;",
      "  float scan=0.94+0.06*sin(gl_FragCoord.y*2.8);",
      "  col*=scan;",
      "  float roll=0.98+0.02*sin(p.y*4.0-u_time*0.6);",
      "  col*=roll;",
      "  col*=smoothstep(1.4, 0.4, length(p));",
      "  gl_FragColor=vec4(col,1.0);",
      "}"
    ].join("\n")
  },
  {
    id: "micro-chromatic",
    name: "Micro Chromatic",
    lote: 2,
    mood: "tiny RGB breath · soft field · no skyline",
    keywords: ["glitch", "rgb-split", "micro", "soft", "chromatic"],
    traits: ["glitch", "rgb-split", "micro", "soft", "chromatic", "density-low", "muted", "section-bg"],
    palette: ["#08090e", "#2a2030", "#3a4850", "#1a1520", "#4a3848"],
    motion: "Atmospheric fog field with micro chromatic offset (1–2px feel) and rare soft pulses — no hard city bars.",
    performance: "Light.",
    fragment: [
      "precision mediump float;",
      "uniform float u_time;",
      "uniform vec2 u_resolution;",
      "varying vec2 v_uv;",
      "float hash(vec2 p){ return fract(sin(dot(p, vec2(12.9898,78.233))) * 43758.5453); }",
      "float noise(vec2 p){",
      "  vec2 i=floor(p); vec2 f=fract(p);",
      "  float a=hash(i); float b=hash(i+vec2(1.0,0.0));",
      "  float c=hash(i+vec2(0.0,1.0)); float d=hash(i+vec2(1.0,1.0));",
      "  vec2 u=f*f*(3.0-2.0*f);",
      "  return mix(mix(a,b,u.x), mix(c,d,u.x), u.y);",
      "}",
      "void main(){",
      "  vec2 uv=gl_FragCoord.xy/u_resolution.xy;",
      "  vec2 p=(gl_FragCoord.xy-0.5*u_resolution.xy)/u_resolution.y;",
      "  float t=u_time;",
      "  float pulse=step(0.97, hash(vec2(floor(t*1.5), 0.3)));",
      "  float shift=(0.0015+0.003*pulse);",
      "  float fr=noise(p*1.8+vec2(shift*40.0, t*0.05));",
      "  float fg=noise(p*1.8+vec2(0.0, t*0.05));",
      "  float fb=noise(p*1.8+vec2(-shift*40.0, t*0.05));",
      "  vec3 base=vec3(0.045, 0.04, 0.055);",
      "  vec3 col=base;",
      "  col.r+=fr*0.12;",
      "  col.g+=fg*0.10;",
      "  col.b+=fb*0.14;",
      "  col=mix(col, col*vec3(1.05, 0.98, 1.08), pulse*0.25);",
      "  float vig=smoothstep(1.35, 0.35, length(p));",
      "  col*=vig;",
      "  gl_FragColor=vec4(col,1.0);",
      "}"
    ].join("\n")
  },
  {
    id: "soft-tear-mist",
    name: "Soft Tear Mist",
    lote: 2,
    mood: "gentle horizontal tears · fog · low drama",
    keywords: ["glitch", "tear", "fog", "soft", "horizontal"],
    traits: ["glitch", "tear", "fog", "soft", "horizontal", "density-low", "muted", "section-bg"],
    palette: ["#07080c", "#1e2430", "#3a4450", "#12161c", "#2a3040"],
    motion: "Soft fog with occasional low-opacity horizontal tear bands that drift — never full-screen hard cuts.",
    performance: "Light.",
    fragment: [
      "precision mediump float;",
      "uniform float u_time;",
      "uniform vec2 u_resolution;",
      "varying vec2 v_uv;",
      "float hash(float n){ return fract(sin(n)*43758.5453); }",
      "float hash2(vec2 p){ return fract(sin(dot(p, vec2(127.1,311.7)))*43758.5453); }",
      "float noise(vec2 p){",
      "  vec2 i=floor(p); vec2 f=fract(p);",
      "  float a=hash2(i); float b=hash2(i+vec2(1.0,0.0));",
      "  float c=hash2(i+vec2(0.0,1.0)); float d=hash2(i+vec2(1.0,1.0));",
      "  vec2 u=f*f*(3.0-2.0*f);",
      "  return mix(mix(a,b,u.x), mix(c,d,u.x), u.y);",
      "}",
      "void main(){",
      "  vec2 uv=gl_FragCoord.xy/u_resolution.xy;",
      "  vec2 p=(gl_FragCoord.xy-0.5*u_resolution.xy)/u_resolution.y;",
      "  float t=u_time*0.25;",
      "  float band=floor(uv.y*18.0+t*0.4);",
      "  float tearOn=step(0.88, hash(band+floor(t*0.8)));",
      "  float tear=tearOn*(hash(band*3.1)-0.5)*0.03;",
      "  vec2 gp=p+vec2(tear, 0.0);",
      "  float fog=noise(gp*1.5+vec2(t*0.3, t*0.2));",
      "  vec3 col=vec3(0.04, 0.045, 0.055);",
      "  col+=vec3(0.14, 0.18, 0.24)*fog*0.32;",
      "  float line=smoothstep(0.02, 0.0, abs(fract(uv.y*18.0+t*0.4)-0.5))*tearOn*0.08;",
      "  col+=vec3(0.2, 0.22, 0.28)*line;",
      "  col*=smoothstep(1.4, 0.4, length(p));",
      "  gl_FragColor=vec4(col,1.0);",
      "}"
    ].join("\n")
  },
  {
    id: "phosphor-grain",
    name: "Phosphor Grain",
    lote: 2,
    mood: "fine grain · cold phosphor · still atmosphere",
    keywords: ["grain", "phosphor", "crt", "soft", "noise"],
    traits: ["grain", "phosphor", "crt", "soft", "noise", "density-low", "blue-green", "section-bg"],
    palette: ["#060908", "#142018", "#2a3a30", "#6a8a70", "#0a0e0c"],
    motion: "Static-ish fine grain over a slow-breathing cool field; almost meditative.",
    performance: "Light — hash grain per pixel.",
    fragment: [
      "precision mediump float;",
      "uniform float u_time;",
      "uniform vec2 u_resolution;",
      "varying vec2 v_uv;",
      "float hash(vec2 p){ return fract(sin(dot(p, vec2(127.1,311.7)))*43758.5453); }",
      "void main(){",
      "  vec2 uv=gl_FragCoord.xy/u_resolution.xy;",
      "  vec2 p=(gl_FragCoord.xy-0.5*u_resolution.xy)/u_resolution.y;",
      "  float t=u_time*0.15;",
      "  float breath=0.5+0.5*sin(t*0.7);",
      "  vec3 col=vec3(0.035, 0.045, 0.04);",
      "  col+=vec3(0.08, 0.14, 0.12)*exp(-length(p+vec2(0.1*sin(t),0.05))*1.2)*0.35;",
      "  col+=vec3(0.05, 0.08, 0.1)*breath*0.08;",
      "  float g=hash(gl_FragCoord.xy+floor(u_time*12.0));",
      "  col+= (g-0.5)*0.035;",
      "  float scan=0.96+0.04*sin(gl_FragCoord.y*3.1);",
      "  col*=scan;",
      "  col*=smoothstep(1.4, 0.35, length(p));",
      "  gl_FragColor=vec4(col,1.0);",
      "}"
    ].join("\n")
  },
  {
    id: "quiet-aurora-wash",
    name: "Quiet Aurora Wash",
    lote: 2,
    mood: "ribbon haze · muted neon · no laser edges",
    keywords: ["aurora", "wash", "soft", "muted", "ribbon"],
    traits: ["aurora", "wash", "soft", "muted", "ribbon", "density-low", "violet", "section-bg"],
    palette: ["#06060c", "#1a1230", "#2a2048", "#3a3860", "#0c0818"],
    motion: "Wide soft sine washes at low opacity — aurora suggestion without bright laser lines.",
    performance: "Light — few sine layers.",
    fragment: [
      "precision mediump float;",
      "uniform float u_time;",
      "uniform vec2 u_resolution;",
      "varying vec2 v_uv;",
      "void main(){",
      "  vec2 uv=(gl_FragCoord.xy-0.5*u_resolution.xy)/u_resolution.y;",
      "  float t=u_time*0.18;",
      "  vec3 col=vec3(0.03, 0.03, 0.055);",
      "  for(int i=0;i<4;i++){",
      "    float fi=float(i);",
      "    float y=uv.y+0.12*sin(uv.x*(1.6+fi*0.35)+t*(0.5+fi*0.08)+fi);",
      "    float band=exp(-pow(y-(fi-1.5)*0.1, 2.0)*18.0);",
      "    vec3 c=mix(vec3(0.15, 0.2, 0.4), vec3(0.35, 0.12, 0.35), fi/3.0);",
      "    col+=c*band*0.14;",
      "  }",
      "  col+=vec3(0.06, 0.04, 0.1)*exp(-length(uv)*1.1)*0.2;",
      "  col*=smoothstep(1.4, 0.35, length(uv));",
      "  gl_FragColor=vec4(col,1.0);",
      "}"
    ].join("\n")
  },
  {
    id: "temporal-whisper",
    name: "Temporal Whisper",
    lote: 2,
    mood: "low jitter · soft static · background-safe glitch",
    keywords: ["glitch", "jitter", "temporal", "static", "soft"],
    traits: ["glitch", "jitter", "temporal", "static", "soft", "density-low", "noise", "section-bg"],
    palette: ["#08080c", "#1c1a24", "#2a2834", "#3a3848", "#101018"],
    motion: "Rare micro temporal jitter of UVs plus soft grain bursts — intensity kept under ~3% displacement.",
    performance: "Light.",
    fragment: [
      "precision mediump float;",
      "uniform float u_time;",
      "uniform vec2 u_resolution;",
      "varying vec2 v_uv;",
      "float hash(float n){ return fract(sin(n)*43758.5453); }",
      "float hash2(vec2 p){ return fract(sin(dot(p, vec2(12.9898,78.233)))*43758.5453); }",
      "float noise(vec2 p){",
      "  vec2 i=floor(p); vec2 f=fract(p);",
      "  float a=hash2(i); float b=hash2(i+vec2(1.0,0.0));",
      "  float c=hash2(i+vec2(0.0,1.0)); float d=hash2(i+vec2(1.0,1.0));",
      "  vec2 u=f*f*(3.0-2.0*f);",
      "  return mix(mix(a,b,u.x), mix(c,d,u.x), u.y);",
      "}",
      "void main(){",
      "  vec2 p=(gl_FragCoord.xy-0.5*u_resolution.xy)/u_resolution.y;",
      "  float t=u_time;",
      "  float burst=step(0.94, hash(floor(t*4.0)));",
      "  vec2 j=vec2(hash(floor(t*8.0))-0.5, hash(floor(t*8.0)+1.7)-0.5)*0.012*burst;",
      "  float f=noise((p+j)*2.0+vec2(t*0.04, -t*0.03));",
      "  vec3 col=vec3(0.04, 0.038, 0.05);",
      "  col+=vec3(0.12, 0.11, 0.16)*f*0.35;",
      "  float grain=hash2(gl_FragCoord.xy+floor(t*20.0));",
      "  col+=(grain-0.5)*0.03*(0.4+0.6*burst);",
      "  col*=smoothstep(1.4, 0.4, length(p));",
      "  gl_FragColor=vec4(col,1.0);",
      "}"
    ].join("\n")
  },
  {
    id: "ghost-lattice",
    name: "Ghost Lattice",
    lote: 2,
    mood: "faint grid breath · teal hush · no horizon rush",
    keywords: ["grid", "ghost", "soft", "teal", "lattice"],
    traits: ["grid", "ghost", "soft", "teal", "lattice", "density-low", "hologram", "section-bg"],
    palette: ["#060a0c", "#0e1a1c", "#1a3030", "#2a4848", "#081014"],
    motion: "Nearly invisible orthographic lattice with slow opacity breath — section texture, not perspective tunnel.",
    performance: "Light.",
    fragment: [
      "precision mediump float;",
      "uniform float u_time;",
      "uniform vec2 u_resolution;",
      "varying vec2 v_uv;",
      "void main(){",
      "  vec2 uv=(gl_FragCoord.xy-0.5*u_resolution.xy)/u_resolution.y;",
      "  float t=u_time*0.2;",
      "  vec2 g=abs(fract(uv*4.5+vec2(t*0.05, -t*0.03))-0.5);",
      "  float line=smoothstep(0.03, 0.0, min(g.x, g.y));",
      "  float breath=0.55+0.45*sin(t*0.9);",
      "  vec3 col=vec3(0.035, 0.045, 0.05);",
      "  col+=vec3(0.08, 0.22, 0.2)*line*0.12*breath;",
      "  col+=vec3(0.04, 0.08, 0.09)*exp(-length(uv)*1.3)*0.25;",
      "  float fog=0.5+0.5*sin(uv.x*2.0+t)*sin(uv.y*1.5-t*0.7);",
      "  col+=vec3(0.03, 0.06, 0.06)*fog*0.1;",
      "  col*=smoothstep(1.4, 0.35, length(uv));",
      "  gl_FragColor=vec4(col,1.0);",
      "}"
    ].join("\n")
  },
  {
    id: "signal-bloom-fog",
    name: "Signal Bloom Fog",
    lote: 2,
    mood: "diffuse neon bloom · fog · no hard orbs",
    keywords: ["bloom", "fog", "neon", "soft", "muted"],
    traits: ["bloom", "fog", "neon", "soft", "muted", "density-low", "magenta-cyan", "section-bg"],
    palette: ["#08060c", "#1a1020", "#2a1838", "#102028", "#0c0a12"],
    motion: "Two large soft color blooms drifting slowly in fog — never sharp specular spheres.",
    performance: "Light.",
    fragment: [
      "precision mediump float;",
      "uniform float u_time;",
      "uniform vec2 u_resolution;",
      "varying vec2 v_uv;",
      "float hash(vec2 p){ return fract(sin(dot(p, vec2(127.1,311.7)))*43758.5453); }",
      "float noise(vec2 p){",
      "  vec2 i=floor(p); vec2 f=fract(p);",
      "  float a=hash(i); float b=hash(i+vec2(1.0,0.0));",
      "  float c=hash(i+vec2(0.0,1.0)); float d=hash(i+vec2(1.0,1.0));",
      "  vec2 u=f*f*(3.0-2.0*f);",
      "  return mix(mix(a,b,u.x), mix(c,d,u.x), u.y);",
      "}",
      "void main(){",
      "  vec2 uv=(gl_FragCoord.xy-0.5*u_resolution.xy)/u_resolution.y;",
      "  float t=u_time*0.15;",
      "  vec2 c1=vec2(sin(t*0.4)*0.35, cos(t*0.3)*0.2);",
      "  vec2 c2=vec2(cos(t*0.35)*0.4, sin(t*0.25)*0.25);",
      "  float b1=exp(-length(uv-c1)*2.2);",
      "  float b2=exp(-length(uv-c2)*2.0);",
      "  float fog=noise(uv*1.4+t*0.2)*0.5+0.5;",
      "  vec3 col=vec3(0.04, 0.035, 0.055);",
      "  col+=vec3(0.35, 0.08, 0.25)*b1*0.22;",
      "  col+=vec3(0.05, 0.28, 0.35)*b2*0.2;",
      "  col+=vec3(0.08, 0.08, 0.12)*fog*0.15;",
      "  col*=smoothstep(1.4, 0.35, length(uv));",
      "  gl_FragColor=vec4(col,1.0);",
      "}"
    ].join("\n")
  },
  {
    id: "subpixel-drift",
    name: "Subpixel Drift",
    lote: 2,
    mood: "scan corruption · micro drift · whisper glitch",
    keywords: ["glitch", "scan", "subpixel", "corruption", "soft"],
    traits: ["glitch", "scan", "subpixel", "corruption", "soft", "density-low", "muted", "section-bg"],
    palette: ["#07080c", "#141820", "#222830", "#2a3040", "#0c1014"],
    motion: "Brief low-opacity scan-row corruption with subpixel horizontal drift — never yellow flash bands or RGB city.",
    performance: "Light.",
    fragment: [
      "precision mediump float;",
      "uniform float u_time;",
      "uniform vec2 u_resolution;",
      "varying vec2 v_uv;",
      "float hash(float n){ return fract(sin(n)*43758.5453); }",
      "float hash2(vec2 p){ return fract(sin(dot(p, vec2(12.9898,78.233)))*43758.5453); }",
      "float noise(vec2 p){",
      "  vec2 i=floor(p); vec2 f=fract(p);",
      "  float a=hash2(i); float b=hash2(i+vec2(1.0,0.0));",
      "  float c=hash2(i+vec2(0.0,1.0)); float d=hash2(i+vec2(1.0,1.0));",
      "  vec2 u=f*f*(3.0-2.0*f);",
      "  return mix(mix(a,b,u.x), mix(c,d,u.x), u.y);",
      "}",
      "void main(){",
      "  vec2 uv=gl_FragCoord.xy/u_resolution.xy;",
      "  vec2 p=(gl_FragCoord.xy-0.5*u_resolution.xy)/u_resolution.y;",
      "  float t=u_time;",
      "  float row=floor(uv.y*48.0);",
      "  float corrupt=step(0.96, hash(row+floor(t*3.0)));",
      "  float drift=(hash(row*2.3)-0.5)*0.008*corrupt;",
      "  vec2 gp=p+vec2(drift, 0.0);",
      "  float f=noise(gp*1.7+vec2(t*0.05, t*0.03));",
      "  vec3 col=vec3(0.04, 0.042, 0.055);",
      "  col+=vec3(0.1, 0.12, 0.16)*f*0.3;",
      "  // micro channel bias only on corrupted rows",
      "  col.r+=corrupt*0.03*f;",
      "  col.b+=corrupt*0.025*(1.0-f);",
      "  float scan=0.97+0.03*sin(gl_FragCoord.y*2.5);",
      "  col*=scan;",
      "  col*=smoothstep(1.4, 0.4, length(p));",
      "  gl_FragColor=vec4(col,1.0);",
      "}"
    ].join("\n")
  }
];
